name: Reusable workflow

on: 
  workflow_call:
    # inputs:
    #     config-path:
    #       required: true
    #       type: string
    #   secrets:
    #     envPAT:
    #       required: true

jobs:
  reusejob1:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      # Checkout the repo 
      - uses: actions/checkout@v3 
        # with:
        #   repo-token: ${{ secrets.envPAT }}
        #   configuration-path: ${{ inputs.config-path }}
      - run: echo "MY REUSABLE JOB 1 - EXECUTED"
      
